apiVersion: apps/v1
kind: Deployment
metadata:
  name: "grafana"
  labels:
    app.kubernetes.io/name: "grafana"
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: "grafana"
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: "grafana"
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: "grafana"
          image: "grafana/grafana-oss" 
          imagePullPolicy: IfNotPresent
          ports:
          - name: http
            containerPort: 3000 
            protocol: TCP

          volumeMounts:
          - mountPath: /etc/grafana/provisioning/datasources
            name: grafana-datasources
            readOnly: false
          - name: grafana
            mountPath: "/var/lib/grafana"
      volumes:
      - name: grafana 
        persistentVolumeClaim:
         claimName: grafana
      - name: grafana-datasources
        configMap:
            defaultMode: 420
            name: grafana
