apiVersion: v1
kind: Service
metadata:
  name: "grafana"
  labels:
    app.kubernetes.io/name: "grafana"
    app.kubernetes.io/instance: {{ .Release.Name }}

spec:
  type: NodePort
  ports:
    - port: 3000
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: "grafana"
    app.kubernetes.io/instance: {{ .Release.Name }}
