apiVersion: apps/v1
kind: Deployment
metadata:
  name: "prometheus"
  labels:
    app.kubernetes.io/name: "prometheus"
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: "prometheus"
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: "prometheus"
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      securityContext:
        runAsUser: 1000
        runAsNonRoot: true
        runAsGroup: 65534
        fsGroup: 2000
      serviceAccountName: "prometheus"
      containers:
        - name: "prometheus"
          image: "prom/prometheus" 
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 9090
              protocol: TCP
          volumeMounts:
            - name: config
              mountPath: /etc/prometheus
            - name: data
              mountPath: /prometheus



      volumes:
        - name: config
          configMap:
            name: prometheus
        - name: data
          persistentVolumeClaim:
             claimName: prometheus

