 
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus
data:
  prometheus.yml: |
      # my global config
      global:
        scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
        evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
      
      scrape_configs:
      - job_name: metrics
        scrape_interval: 5s
        kubernetes_sd_configs:
        - role: pod
          namespaces:
            names:
            - default
          selectors:
          - role: pod
            label: "metrics=rustometer"


