apiVersion: v1
kind: Service
metadata:
  name: "rustometer"
  labels:
    app.kubernetes.io/name: "rustometer"
    app.kubernetes.io/instance: {{ .Release.Name }}

spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
    - port: 9090
      targetPort: prometheus
      protocol: TCP
      name: prometheus

  selector:
    app.kubernetes.io/name: "rustometer"
    app.kubernetes.io/instance: {{ .Release.Name }}
