apiVersion: apps/v1
kind: Deployment
metadata:
  name: "rustometer"
  labels:
    app.kubernetes.io/name: "rustometer"
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: "rustometer"
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        metrics: "rustometer"
        app.kubernetes.io/name: "rustometer"
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: "rustometer"
          image: {{ .Values.rustometer }}
          imagePullPolicy: IfNotPresent
          env:
          - name:  RUST_LOG
            value: rustometer=info

          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
            - name: prometheus
              containerPort: 9090
              protocol: TCP



