apiVersion: apps/v1
kind: Deployment
metadata:
  name: "zipkin"
  labels:
    app.kubernetes.io/name: "zipkin"
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: "zipkin"
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: "zipkin"
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: "zipkin"
          image: "openzipkin/zipkin" 
          imagePullPolicy: IfNotPresent
          args: ["--reporter.tchannel.host-port=zipkin:14267"]
          ports:
          - containerPort: 9411
            protocol: TCP

