apiVersion: v1
kind: Service
metadata:
  name: "zipkin"
  labels:
    app.kubernetes.io/name: "zipkin"
    app.kubernetes.io/instance: {{ .Release.Name }}

spec:
  type: NodePort
  ports:
    - port: 9411
      targetPort: 9411
      protocol: TCP
      name: http

  selector:
    app.kubernetes.io/name: "zipkin"
    app.kubernetes.io/instance: {{ .Release.Name }}
